import Head from "next/head";

import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";

export default function Home({ exploreData, cardsData }) {
  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          {/* PULL SOME DATA FROM A SERVER - API ENDPOINTS */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, distance, location }) => (
              <SmallCard
                distance={distance}
                img={img}
                key={img}
                location={location}
              />
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
              {cardsData?.map(({ img, title }) => (
                <MediumCard img={img} key={img} title={title} />
              ))}
          </div>
        </section>
        <LargeCard buttonText="Get Inspired" description="Wishlists curated by Airbnb." img="https://links.papareact.com/4cj" title="The Greatest Outdoors" />
      </main>

      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/3XOF").then((res) => res.json());

  const cardsData = await fetch("https://www.jsonkeeper.com/b/EDN3").then((res) => res.json());

  return {
    props: {
      cardsData,
      exploreData
    }
  };
}
